import { AppShell } from "@/components/app-shell";
import { listMessageDrafts } from "@/lib/supabase/queries";

export default async function MessagesPage() {
  const messages = await listMessageDrafts();

  return (
    <AppShell>
      <div className="px-5 py-5 sm:px-8">
        <h1 className="text-2xl font-semibold">Message Studio</h1>
        <p className="mt-1 text-sm text-[#a3a3a3]">
          Draft-only LinkedIn, email, sponsor, partner, speaker, and nurture messages.
        </p>
        <div className="mt-5 rounded-md border border-[#2a2a2a] bg-[#111111]">
          {messages.length === 0 ? (
            <p className="p-4 text-sm">Messages generated by AI will remain in draft status until approved by a human.</p>
          ) : (
            <div className="divide-y divide-[#242424]">
              {messages.map((message) => (
                <article className="space-y-2 p-4" key={message.id}>
                  <div className="flex flex-wrap items-center gap-2">
                    <span className="rounded-md bg-[#1f0a0a] px-2 py-1 text-xs text-[#ef4444]">{message.channel}</span>
                    <span className="rounded-md bg-[#1a1a1a] px-2 py-1 text-xs text-[#a3a3a3]">{message.message_type}</span>
                    <span className="rounded-md bg-[#2a0f0f] px-2 py-1 text-xs text-[#fca5a5]">{message.status}</span>
                  </div>
                  {message.subject ? <h2 className="font-medium">{message.subject}</h2> : null}
                  <p className="whitespace-pre-wrap text-sm text-[#d4d4d4]">{message.body}</p>
                </article>
              ))}
            </div>
          )}
        </div>
      </div>
    </AppShell>
  );
}
