import { AppShell } from "@/components/app-shell";
import { listMessageDrafts } from "@/lib/supabase/queries";

export default async function MessagesPage() {
  const messages = await listMessageDrafts();

  return (
    <AppShell>
      <div className="px-5 py-5 sm:px-8">
        <h1 className="text-2xl font-semibold">Message Studio</h1>
        <p className="mt-1 text-sm text-[#69746d]">
          Draft-only LinkedIn, email, sponsor, partner, speaker, and nurture messages.
        </p>
        <div className="mt-5 rounded-md border border-[#d8ded5] bg-white">
          {messages.length === 0 ? (
            <p className="p-4 text-sm">Messages generated by AI will remain in draft status until approved by a human.</p>
          ) : (
            <div className="divide-y divide-[#edf0ea]">
              {messages.map((message) => (
                <article className="space-y-2 p-4" key={message.id}>
                  <div className="flex flex-wrap items-center gap-2">
                    <span className="rounded-md bg-[#e4eee9] px-2 py-1 text-xs text-[#1f6f5b]">{message.channel}</span>
                    <span className="rounded-md bg-[#f3f4f0] px-2 py-1 text-xs text-[#69746d]">{message.message_type}</span>
                    <span className="rounded-md bg-[#fff1d6] px-2 py-1 text-xs text-[#6b5424]">{message.status}</span>
                  </div>
                  {message.subject ? <h2 className="font-medium">{message.subject}</h2> : null}
                  <p className="whitespace-pre-wrap text-sm text-[#34413a]">{message.body}</p>
                </article>
              ))}
            </div>
          )}
        </div>
      </div>
    </AppShell>
  );
}
