import { AppShell } from "@/components/app-shell";

export default function MessagesPage() {
  return (
    <AppShell>
      <div className="px-5 py-5 sm:px-8">
        <h1 className="text-2xl font-semibold">Message Studio</h1>
        <p className="mt-1 text-sm text-[#69746d]">
          Draft-only LinkedIn, email, sponsor, partner, speaker, and nurture messages.
        </p>
        <div className="mt-5 rounded-md border border-[#d8ded5] bg-white p-4 text-sm">
          Messages generated by AI will remain in draft status until approved by a human.
        </div>
      </div>
    </AppShell>
  );
}
